### ISSUE TITLE
Popup with preview cannot be closed

### ISSUE THREAD

**Issue by pkraker** [pkraker/Headstart#24]
JavaScript console output: uncaught exception: event show inappropriate in current state visible

**Comment by Bubblbu** [comment]
At the moment clicking on "Preview PDF" opens a new tab with the document url to PLOS. Can't really reproduce/test the bug

**Comment by pkraker** [comment]
This is a quick fix related to #24 that is only implemented on openknowledgemaps.org. You should be able to reproduce the problem on a local test system.
