### ISSUE TITLE
Search & filter: multiple keywords are only highlighted when they are adjacent

### ISSUE THREAD

**Issue by pkraker** [pkraker/Headstart#27]
Search allows you to filter using multiple keywords separated by space, even if they are not in a phrase, searching for e.g. "technology learning" finds entries with "technology enhanced learning". But the words currently don't get highlighted.

**Comment by Bubblbu** [comment]
462b27c2589759b8ed79224075ecacbb2386341f fixed this behaviour. Also added css class "highlightable" in order to enable highlighting on element. Also this new solution should perform better
