### ISSUE TITLE
Pubmed search

### ISSUE THREAD

**Issue by pkraker** [pkraker/Headstart#40]
It would be awesome to extend the search functionalty to Pubmed. This would require to conduct a search in Pubmed and to retrieve basic metadata, abstract and categories for the first 100 papers. For display purposes in the visualization, we will also need to retrieve the full text PDF on demand (if it's available).

**Comment by sckott** [comment]
Sounds good. how best to integrate into the codebase?

**Comment by pkraker** [comment]
I have now written a modular version of the R scripts. The idea is to have a script for every API. Each script provides a get_papers function that returns metadata and text for the search results.

I have created a stub for the Pubmed search that includes a description: https://github.com/pkraker/Headstart/blob/master/server/preprocessing/other-scripts/pubmed.R

For reference, see the PLOS script that implements the get_papers() function: https://github.com/pkraker/Headstart/blob/master/server/preprocessing/other-scripts/rplos_fast.R

For testing purposes, have a look at the following script. It performs the whole query and analysis part: https://github.com/pkraker/Headstart/blob/master/server/preprocessing/other-scripts/test/rplos_fast-test.R

**Comment by sckott** [comment]
working on it

**Comment by pkraker** [comment]
Nice! I had to switch out xml2::xml_find_first with xml2::xml_find_one to get it to work. Which version of xml2 are you using? Also, searching with query="tomato" and params=NULL leads to a warning (and a subsequent error) that there are rows with the same name.

**Comment by sckott** [comment]
Sorry, i am on the dev version of `xml2`. and that fxn name changed in the dev version.

> Also, searching with query="tomato" and params=NULL leads to a warning (and a subsequent error) that there are rows with the same name.

did you already update the function, so i can test what you have

**Comment by pkraker** [comment]
Sorry, just pushed my changes. Maybe some of my other edits are to blame.

**Comment by sckott** [comment]
using the latest code you have that works for me, let me know if that still is broken for you

**Comment by pkraker** [comment]
Thanks, let me close this one then. I'll open separate issues, if I run into any problems.
