### ISSUE TITLE
sorting algorithm

### ISSUE THREAD

**Issue by brembs** [pkraker/Headstart#43]
I don't yet know how representative my current search is so I'll expand on my searches, but one issue I noticed was that my technical term 'operant' was expanded to 'operative' and 'operating', neither of which are synonyms. Hence, the groupings are too often off-topic.
I realize that this is likely not completely trivial, but there likely needs to be some list of technical terms in the background. How about using the various ontologies? For instance, gene ontology is widely used and should be quite up to date. I haven't checked it in a while, but there are numerous behavior-related terms in GO and 'operant' might be there along with related concepts.
But perhaps these ontologies are already incorporated and just need to be corrected?

**Comment by pkraker** [comment]
Thanks for your feedback. That's indeed not a very good behaviour. 

At the moment, we rely completely on the PLOS API (through rplos) to deliver the search results, and it seems that they have turned on query expansion by default. I don't know what kind of query expansion they are using, but it seems that they do not have scientific ontologies in the background. I also haven't found a quick way to turn query expansion off (maybe @sckott knows more about that?). The only solution that seems to work is to use a phrase search, i.e. putting your search words in quotes. But that seems to work only when there are two or more search terms.

**Comment by chreman** [comment]
at a first guess I'd say this is an artefact from indexing (after applying some sort of stemming procedure all three words can be collapsed to "opera") and will be returned with the same score after a search. If you could point me to the relevant section in the code I can have a closer look.

**Comment by sckott** [comment]
I am no Solr expert, so not sure off the top what solution is. I do have the PLOS Solr schema, but for some reason they don't want it to be public (i'll share in slack) - I haven't yet moved to using my Solr client `solrium` inside the `searchplos()` function, so there's lots of Solr parameters that could be used, but aren't allowed - I'll rework to use the `solrium` client - We also may want to just get back json or xml (whichever you prefer) and avoid the internal parsing to data.frame's useful for R users, but probably not needed in this case

**Comment by brembs** [comment]
What about implementing ontologies? Is that even on the horizon, or just pie in the sky for now?

**Comment by pkraker** [comment]
@sckott: I think we can simply use everything_rev for now.
@brembs: Please take a look at the current version on the server which avoids query expansion. As to the ontologies: that's definitely on the horizon. It is one of the main features of @hmetaxa's topic modeling engine.

**Comment by sckott** [comment]
Can you list some example searches, and what you expect to see ?

**Comment by pkraker** [comment]
@brembs has confirmed that this issue has been solved by using everything_rev instead of everything. I'll close this issue and open a feature request for using ontologies to improve search results.
