### ISSUE TITLE
Encoding of Pubmed results

### ISSUE THREAD

**Issue by pkraker** [pkraker/Headstart#52]
I am having problems with processing the output of Pubmed and I am pretty sure that they are encoding-related. When I check the encoding with `Encoding(metadata$abstract)`, the result is `"Unknown"`. Is it possible that everything that comes back from `get_papers` is UTF-8 encoded?

**Comment by sckott** [comment]
will do

**Comment by sckott** [comment]
Can you give example of the bad output?

**Comment by pkraker** [comment]
I have investigated this issue further and it seems that the problem is not so much that the results from Pubmed are not UTF-8 encoded (they actually are), but that the encoding is not declared. That seems to lead to problems once the results are converted to JSON. It could be that `toJSON ` assumes that the encoding is plain text if there is no encoding declared. A solution could be to apply something like `Encoding(x) <- "UTF-8"` to the whole result table in `get_papers`.

**Comment by sckott** [comment]
note to self: search for `tomato`

**Comment by sckott** [comment]
looking at this now

**Comment by pkraker** [comment]
The encoding is correctly declared in version 1.0 of xml2.
