### ISSUE TITLE
Responsive design: Same screen size results in different representations

### ISSUE THREAD

**Issue by pkraker** [pkraker/Headstart#53]
Steps to reproduce:
1) Load visualization
2) Resize window so that it becomes smaller than the visualization
3) Resize window to its original size 

Now the representation will be different than after step 1 (Smaller bubbles, smaller fonts etc.).

**Comment by Bubblbu** [comment]
I am not completely sure, but does 2fe44747e666d329de95a3a8151b6a10b7fb623d resolve the problems?

**Comment by pkraker** [comment]
Yep, that works for me now!
