### ISSUE TITLE
Responsive design: Papers are outside of bubbles on zoom in

### ISSUE THREAD

**Issue by pkraker** [pkraker/Headstart#54]
This issue only occurs on small screen sizes (see image attached).

![error_responsive](https://cloud.githubusercontent.com/assets/6399997/16956208/da42bd0e-4dd7-11e6-9b7c-574e3fc0fdd0.png)

**Comment by Bubblbu** [comment]
Duplicate #59

**Comment by pkraker** [comment]
Closing as this is a duplicate.
