### ISSUE TITLE
Error: No matches in pubmed.R

### ISSUE THREAD

**Issue by pkraker** [pkraker/Headstart#55]
I have committed a version to the pubmed_integration branch that creates a visualization for the search term "tomato". Unfortunately, most other terms produce `Error: No matches`, which seem to occur on lines 58 and 59 of `pubmed.R` and involve the `xml_find_one` function. The error can easily be reproduced by running `pubmed-test.R` in `server/preprocessing/other-scripts/test`.

**Comment by sckott** [comment]
thanks, will do

**Comment by sckott** [comment]
@pkraker that `server/preprocessing/other-scripts/test/pubmed-test.R` doesn't exist, which file are you referrring to

**Comment by sckott** [comment]
possibly this one https://github.com/pkraker/Headstart/blob/master/server/preprocessing/other-scripts/test/curl_test.R

**Comment by sckott** [comment]
ah i see it not on master
