### ISSUE TITLE
Responsive design: on zoom in, papers are moving towards center of bubble

### ISSUE THREAD

**Issue by pkraker** [pkraker/Headstart#56]
Papers move to the center of the bubble when zoomed. You can see in the images below that papers do overlap that haven't overlapped in the zoomed out state. Also, papers are further away from the confining circle than they should.

![zoom_error_1](https://cloud.githubusercontent.com/assets/6399997/17207480/1155ddf6-54b5-11e6-873e-00ca1c1c912e.png)
![zoom_error_2](https://cloud.githubusercontent.com/assets/6399997/17207436/e25324aa-54b4-11e6-9afb-63897ef9ccaa.png)

**Comment by Bubblbu** [comment]
Duplicate #59

**Comment by pkraker** [comment]
Closing, as this is a duplicate.
